project:
  type: website
  output-dir: docs

website:
  title: "Efrain's Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio-project/project-portfolio.qmd
        text: "Example Project"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

project:
  type: website